# open windows in same directory
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

set-window-option -g mode-keys vi

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# mouse
set -g mouse on

# vim fixer
set -sg escape-time 0

# count the panes from 1
set -g base-index 1
setw -g pane-base-index 1

# rwxrob's status bar
set -g status-style "fg=#665c54"
set -g status-left-style "fg=#928374"

set -g status-bg default
set -g status-position top
set -g status-left ""

set -g status-right "#(cat /sys/class/power_supply/BAT1/capacity)% %H:%M #(pomo)"
set -g status-interval 1
